# Netlify CMS Configuration for bensfotografie.nl

# Specifies the backend integration. 'git-gateway' allows Netlify Identity
# users to push directly to the Git repository.
backend:
  name: git-gateway
  branch: main # IMPORTANT: Change this to 'master' if your main branch is named master

# Specifies where uploaded media files should be stored IN THE REPOSITORY
media_folder: "static/img/uploads" # <<< Change this path

# Specifies the public URL path for accessing the media files stored in
# 'media_folder'. This path should be relative to the site root.
public_folder: "/img/uploads"

# Defines the content types (collections) manageable via the CMS.
collections:
  # This collection manages the galleries, where each country has ONE file
  # containing a list of its photos.
  - label: "Gallerij" # How the collection is named in the CMS UI
    name: "gallery"   # Internal identifier for this collection
    description: "Beheer hier de foto's per land. Klik op een land om de foto's te wijzigen."
    # 'files' collection type means we edit specific, pre-defined files.
    files:
      # Configuration for the Canada gallery
      - label: "Canada" # Label shown in the CMS UI for this file entry
        name: "canada"  # Internal identifier for this file entry
        # The EXACT path to the file this entry will edit in the repository.
        # Make sure this file exists (content/gallery/canada.md).
        file: "content/gallery/canada.md"
        fields:
          # Optional: A title field for the country page itself
          - { label: "Titel (optioneel)", name: "title", widget: "string", required: false, default: "Canada" }
          # The list of photos for this country
          - label: "Foto's voor Canada"
            name: photos # This name MUST match the front matter key used in Eleventy templates
            widget: list # Allows adding multiple items (images in this case)
            summary: "{{fields.image}}" # Shows a preview of the image in the list UI
            # Defines the field within each list item (just an image field)
            field: { label: "Afbeelding", name: "image", widget: "image" }

      # Configuration for the Colombia gallery
      - label: "Colombia"
        name: "colombia"
        file: "content/gallery/colombia.md" # Make sure this file exists
        fields:
          - { label: "Titel (optioneel)", name: "title", widget: "string", required: false, default: "Colombia" }
          - label: "Foto's voor Colombia"
            name: photos
            widget: list
            summary: "{{fields.image}}"
            field: { label: "Afbeelding", name: "image", widget: "image" }

      # Configuration for the Costa Rica gallery
      - label: "Costa Rica"
        name: "costa-rica" # Use hyphens for consistency if file slug uses hyphen
        file: "content/gallery/costa-rica.md" # Make sure this file exists
        fields:
          - { label: "Titel (optioneel)", name: "title", widget: "string", required: false, default: "Costa Rica" }
          - label: "Foto's voor Costa Rica"
            name: photos
            widget: list
            summary: "{{fields.image}}"
            field: { label: "Afbeelding", name: "image", widget: "image" }

      # Configuration for the Netherlands gallery
      - label: "Nederland"
        name: "netherlands"
        file: "content/gallery/netherlands.md" # Make sure this file exists
        fields:
          - { label: "Titel (optioneel)", name: "title", widget: "string", required: false, default: "Nederland" }
          - label: "Foto's voor Nederland"
            name: photos
            widget: list
            summary: "{{fields.image}}"
            field: { label: "Afbeelding", name: "image", widget: "image" }

# End of configuration